# Dockerfile for Wellnessmodel (model API)
FROM python:3.9-slim

# Set the working directory
WORKDIR /Fastapi-backend

# 로컬 requirements.txt 파일을 컨테이너에 복사
COPY requirements.txt /Fastapi-backend/

# requirements.txt에 명시된 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY ./Wellnessmodel/app /Fastapi-backend
COPY ./Wellnessmodel/app/KJSmodelTest_0921.pth /Fastapi-backend

# 모델 API 실행
CMD ["uvicorn", "model_api:app", "--reload",  "--host", "0.0.0.0", "--port", "8001"]

