version: '3'

services:
  wellnessapp:
    build:
      context: .
      dockerfile: Wellnessapp/Dockerfile
    container_name: wellnessapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

  wellnessmodel:
    build:
      context: .
      dockerfile: Wellnessmodel/Dockerfile-model
    container_name: wellnessmodel
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
